# Actividad
(Haz doble clic en esta celda y completa los datos correspondientes a tu equipo)

Equipo 1
- Juan Daniel Rodríguez Oropeza A01411625
- Rodolfo Gerardo Peña Eraña A01721635
- Jackeline Conant Rubalcava A01280544

# Entregar 
Archivo PDF de la actividad y la liga de la actividad en su repostitorio.

# Nota: 
Las tareas 1 a la 5 se califican como entregadas o no entregadas.

Al integrante que no participe en la actividad no se le tomará en cuenta para la calificación.

El límite para entregar las actividades es el viernes antes de las 23:59.

In [1]:
# Si trabajamos en Google Colaboratory corremos las siguientes lineas de código
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive

In [2]:
# Nos cambiamos a la carpeta donde tengamos el repositorio. Si es otra carpeta asegúrate de cambiar la ruta.
%cd /gdrive/MyDrive/SemanaTec/arte-analitica

/gdrive/MyDrive/SemanaTec/arte-analitica

# Insurance dataset

El dataset contiene información demográfica sobre los asegurado en una compañía de seguros:

- age: edad del asegurado principal
- sex: género del asegurado. female o male
- bmi: índice de masa corporal
- children: numero de niños que estan cubiertos con la poliza. 
- smoke: si fuma el beneficiario. yes/no
- region: dónde vive el beneficiario. Estos datos son de Estados Unidos. Regiones disponibles: northeast, southeast, southwest, northwest
- charges: costo del seguro.

# Actividad
Carga el dataset  **`data/insurance.csv`** y haz un análisis estadístico de las variables.

In [3]:
# Carga las librerías necesarias
import numpy as np
import pandas as pd

In [5]:
# Carga los datos y muestra los primeros renglones
insurance = pd.read_csv('data/insurance.csv')

insurance.head(4)

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061

In [6]:
# Crea una tabla resumen con los estadísticos generales de las variables numéricas
insurance.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [8]:
# ¿Cómo se correlacionan las variables numéricas entre sí?
# ¿Cuáles son las variables que tienen más correlación con los costos del seguro?

insurance.corr()
# Las variables que tienen más correlación son charges y age con 0.299008

               age       bmi  children   charges
age       1.000000  0.109272  0.042469  0.299008
bmi       0.109272  1.000000  0.012759  0.198341
children  0.042469  0.012759  1.000000  0.067998
charges   0.299008  0.198341  0.067998  1.000000

In [11]:
# ¿Cuántas asegurados son hombres y cuántas son mujeres?
insurance['sex'].value_counts()

# Son 676 hombres y 662 mujeres, formando un total 1338 personas.

male      676
female    662
Name: sex, dtype: int64

In [12]:
# ¿Cuántos hombres y mujeres asegurados viven en cada región?
pd.crosstab(insurance['sex'],insurance['region'])

region  northeast  northwest  southeast  southwest
sex
female        161        164        175        162
male          163        161        189        163

In [18]:
# En promedio, ¿quién paga más de cuota de seguro, los fumadores o no fumadores? Muéstralo con los datos
insurance.groupby('smoker').mean()[['charges']]

# Los fumadores pagan más cuota de seguro.

             charges
smoker
no       8434.268298
yes     32050.231832

In [16]:
# De la pregunta anterior, quien tiene más variación (desviación estándar) en la cuota de seguro, 
# ¿los fumadores o los no fumadores?
insurance.groupby('smoker').std()[['charges']]

# Los fumadores tienen más variación en la cuota de seguro.

             charges
smoker
no       5993.781819
yes     11541.547176

In [21]:
# ¿Cuáles son los cargos mínimos y máximos que las personas pagan dependiendo del género?
insurance.groupby('sex').agg(['min', 'max'])[['charges']]

          charges
              min          max
sex
female  1607.5101  63770.42801
male    1121.8739  62592.87309

# Guardar el resultado como pdf

* Escribe aquí abajo la liga de tu repositorio.

* (Haz doble clic en esta celda y copia la URL dentro del paréntesis)

[Liga al repositorio de Equipo 1](https://github.com/A01411625/semanatec-mayo-22)

* Exporta el notebook a formato HTML.

In [24]:
! jupyter nbconvert --to HTML '/gdrive/MyDrive/SemanaTec/arte-analitica/4.2 - Actividad - Estadisticas de datos.ipynb'

[NbConvertApp] Converting notebook /gdrive/MyDrive/SemanaTec/arte-analitica/4.2 - Actividad - Estadisticas de datos.ipynb to HTML
[NbConvertApp] Writing 314361 bytes to /gdrive/MyDrive/SemanaTec/arte-analitica/4.2 - Actividad - Estadisticas de datos.html

* Haz doble clic en el archivo nuevo que se creó dentro de la carpeta `arte-analitica` y en la parte superior derecha dale clic en **imprimir**

* Imprime el archivo como *PDF* y súbelo a Canvas.